[project]
name = "maplink"
version = "0.1.0"
description = "Simple python utility for making symbolic links"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
